# Generated by Django 4.1.5 on 2023-02-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JOKES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke_text', models.CharField(max_length=100)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
            ],
        ),
    ]
